"""initial schema

Revision ID: 56398316e3d9
Revises: 
Create Date: 2026-09-07 00:26:06.477461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56398316e3d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('merchant_id', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('device_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.String(length=50), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_events_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_events_transaction_id'), ['transaction_id'], unique=True)

    op.create_table('risk_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('failure_category', sa.String(length=30), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('recovery_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_source', sa.String(length=20), nullable=True),
    sa.Column('recommended_action', sa.String(length=120), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('signals_json', sa.Text(), nullable=True),
    sa.Column('ml_risk', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('behavioral_risk', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('network_risk', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rule_severity', sa.String(length=10), nullable=True),
    sa.Column('behavioral_json', sa.Text(), nullable=True),
    sa.Column('network_json', sa.Text(), nullable=True),
    sa.Column('audit_json', sa.Text(), nullable=True),
    sa.Column('explanation_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['payment_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_decisions')
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_events_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payment_events_customer_id'))

    op.drop_table('payment_events')
    # ### end Alembic commands ###
