"""decision feedback

Revision ID: c369c235df09
Revises: 56398316e3d9
Create Date: 2026-09-07 13:50:17.660967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c369c235df09'
down_revision: Union[str, Sequence[str], None] = '56398316e3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('analyst', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['risk_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_feedback_decision_id'), ['decision_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_feedback_decision_id'))

    op.drop_table('decision_feedback')
    # ### end Alembic commands ###
